/*
 * This source file was generated by the Gradle 'init' task
 */
package ndswappricing;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

import ndswappricing.NdfPricingMultiCurveBootstrap.YieldCurve;

public class App {

    public static void ndsMultiCurveBootstrapRunner() {
        /* Case 4: NDS pricing using multi-curve bootstrapping */
        System.out.println("Starting Multi-Curve Bootstrapping Simulation (Jan 2026)...");

        // Step A: Build USD OIS Curve (Discount Curve)
        YieldCurve usdOisCurve = new YieldCurve();
        usdOisCurve.addNode(0.0, 0.040); // Instantaneous
        usdOisCurve.addNode(1.0, 0.042); // 1Y OIS Rate

        // Step B: Build CNY OIS Curve (Discount Curve)
        YieldCurve cnyOisCurve = new YieldCurve();
        cnyOisCurve.addNode(0.0, 0.020);
        cnyOisCurve.addNode(1.0, 0.025);

        // Step C: Build USD Forecast Curve (Projection Curve)
        // In multi-curve, Libor/SOFR Term curves are higher than OIS
        YieldCurve usdForecastCurve = new YieldCurve();
        usdForecastCurve.addNode(1.0, 0.048); 

        // Step D: Calculate NDF Price for different cases
        double spotUSDCNY = 7.15;
        double tenor1Y = 1.0;

        double ndfPrice = NdfPricingMultiCurveBootstrap.priceNdfMultiCurve(
            spotUSDCNY, 
            tenor1Y, 
            usdOisCurve, 
            cnyOisCurve, 
            usdForecastCurve
        );

        System.out.printf("Case: 1Y USD/CNY NDF%n");
        System.out.printf("Market Spot: %.4f%n", spotUSDCNY);
        System.out.printf("Multi-Curve NDF Forward: %.6f%n", ndfPrice);
        
        // Example of "Different Cases" - Handling Basis Spreads
        double basisSpread = 0.0050; // 50 bps spread in liquidity
        usdForecastCurve.addNode(1.0, 0.048 + basisSpread);
        double ndfPriceWithSpread = NdfPricingMultiCurveBootstrap.priceNdfMultiCurve(spotUSDCNY, tenor1Y, usdOisCurve, cnyOisCurve, usdForecastCurve);
        
        System.out.printf("Multi-Curve NDF Forward (with 50bps Basis Spread): %.6f%n", ndfPriceWithSpread);
    }
    public static void main(String[] args) {
        /* Case 1: Simple pricing case */
        // Market Data
        double spotRateUSDCNY = 6.4500; // USD is base, CNY is quote
        double usdInterestRate = 0.005; // 0.5%
        double cnyInterestRate = 0.025; // 2.5%
        int dayCount = 360; // Common for FX markets
        
        LocalDate today = LocalDate.of(2026, 1, 26);
        LocalDate settlement = LocalDate.of(2026, 4, 26); // 3 months later

        // Calculate the NDF rate used to price the initial swap
        double calculatedForwardRate = NdfSimplePricingCases.calculateNdfForwardRate(
            spotRateUSDCNY, 
            usdInterestRate, 
            cnyInterestRate, 
            settlement, 
            today, 
            dayCount);
            
        System.out.printf("Calculated 3-month NDF Forward Rate (USD/CNY): %.6f\n", calculatedForwardRate);

        // --- At Maturity/Fixing Date Simulation ---
        
        double tradeAgreedRate = calculatedForwardRate; // The rate we just calculated/agreed to
        double marketFixingRateAtMaturity = 6.4800; // The actual spot rate on the fixing date
        double notionalUSD = 1_000_000.00;
        
        double cashSettlement = NdfSimplePricingCases.calculateNdfSettlement(
            tradeAgreedRate, 
            marketFixingRateAtMaturity, 
            notionalUSD,
            1.0); // Settling in USD (value of 1 USD is 1 USD)
            
        System.out.printf("If market fixes at %.4f, cash settlement amount (in USD): $%,.2f\n", 
                          marketFixingRateAtMaturity, cashSettlement);

        /* Case 2: Different cases in simple NDS pricing */    
        System.out.println("--- NDF Pricing Different Cases ---");
        System.out.println("Valuation Date: " + today + "\n");

        // Case 1: Standard USD/CNY (3 months tenor)
        // High CNY rate drives the forward rate higher than spot (premium)
        double spot1 = 6.4500;
        double rateBase1 = 0.005; // USD rate
        double rateQuote1 = 0.025; // CNY rate
        LocalDate settlement1 = LocalDate.of(2026, 4, 26);
        double forwardRate1 = NdfSimplePricingCases.calculateNdfForwardRate(spot1, rateBase1, rateQuote1, settlement1, today, 360);
        System.out.printf("Case 1 (USD/CNY 3M): Spot=%.4f, BaseRate=%.3f%%, QuoteRate=%.3f%% -> ForwardRate=%.6f\n", 
                          spot1, rateBase1*100, rateQuote1*100, forwardRate1);

        // Case 2: Different Tenor (1 year USD/CNY)
        // Longer tenor magnifies the interest rate differential effect (premium/discount)
        LocalDate settlement2 = LocalDate.of(2026, 1, 26).plusYears(1);
        double forwardRate2 = NdfSimplePricingCases.calculateNdfForwardRate(spot1, rateBase1, rateQuote1, settlement2, today, 360);
        System.out.printf("Case 2 (USD/CNY 1Y): Same rates, Longer tenor -> ForwardRate=%.6f\n", forwardRate2);

        // Case 3: Different Currency Pair (USD/BRL - Brazilian Real)
        // BRL often has very high local rates (large rate differential), leading to a large forward premium
        double spot3 = 5.0000;
        double rateBase3 = 0.005; // USD rate
        double rateQuote3 = 0.100; // BRL rate (10%)
        LocalDate settlement3 = LocalDate.of(2026, 4, 26);
        double forwardRate3 = NdfSimplePricingCases.calculateNdfForwardRate(spot3, rateBase3, rateQuote3, settlement3, today, 360);
        System.out.printf("Case 3 (USD/BRL 3M): Spot=%.4f, QuoteRate=%.1f%% -> ForwardRate=%.6f (High Premium)\n", 
                          spot3, rateQuote3*100, forwardRate3);
                          
        // Case 4: Inverse Interest Differential (Base currency rate higher)
        // This results in a discount (forward rate < spot rate)
        double spot4 = 1.2000; // EUR/USD (EUR base, USD quote)
        double rateBase4 = 0.030; // EUR rate (3%)
        double rateQuote4 = 0.005; // USD rate (0.5%)
        LocalDate settlement4 = LocalDate.of(2026, 4, 26);
        double forwardRate4 = NdfSimplePricingCases.calculateNdfForwardRate(spot4, rateBase4, rateQuote4, settlement4, today, 360);
        System.out.printf("Case 4 (EUR/USD 3M): BaseRate>QuoteRate -> ForwardRate=%.6f (Discount)\n", forwardRate4);

        /* Case 3: NDS Pricing via MC simulations */
        double currentSpot = 6.4500;
        double riskFreeRate = 0.015; // Example average risk-free rate
        double volatility = 0.10; // 10% annualized volatility
        LocalDate fixingDate = LocalDate.of(2026, 4, 26);
        int numSimulations = 10000;
        
        double sumOfPayoffs = 0;
        double agreedNdfRate = 6.5000; // Rate agreed upon at trade start

        for (int i = 0; i < numSimulations; i++) {
            double simulatedFixingRate = NdfPricingMC.simulateFutureSpotRate(currentSpot, riskFreeRate, volatility, today, fixingDate);
            // Payoff is settled in the quote currency's value (typically USD in NDFs)
            // Payoff = Notional (Base) * (AgreedRate - FixingRate) / FixingRate (if settling in Quote currency) 
            // Or simpler (as in previous code, settled in value of 1 USD=1USD): 
            double payoff = notionalUSD * (agreedNdfRate - simulatedFixingRate); 
            sumOfPayoffs += payoff;
        }

        double averagePayoff = sumOfPayoffs / numSimulations;
        // Discount the average payoff back to today (simplified PV calculation)
        long daysBetween = ChronoUnit.DAYS.between(today, fixingDate);
        double timeToMaturity = (double) daysBetween / 365.0;
        double presentValue = averagePayoff * Math.exp(-riskFreeRate * timeToMaturity);

        System.out.printf("Estimated Present Value of NDF via Monte Carlo: $%,.2f\n", presentValue);
        ndsMultiCurveBootstrapRunner();
    }
}
