/*
 * This source file was generated by the Gradle 'init' task
 */
package ndswappricing;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void ndsRunnner() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "main runner class cant be null");
    }
}
